{"uid":"88665c8383de55ab","name":"test_case[dic2]","fullName":"testCase.test_case.TestCase#test_case","historyId":"a63b8a1844343c2264218d24a469d237","time":{"start":1683367561720,"stop":1683367561951,"duration":231},"status":"failed","statusMessage":"AssertionError: 预期结果与实际结果不符，预期结果：{'errorCode':'0'},实际结果：0\nassert '0' == \"{'errorCode':'0'}\"\n  - {'errorCode':'0'}\n  + 0","statusTrace":"self = <testCase.test_case.TestCase object at 0x11023a320>\ndic = {'caseid': '', 'expect': \"{'errorCode':'0'}\", 'header': '{}', 'id': 3.0, ...}\n\n    @pytest.mark.parametrize(\"dic\", test_data)\n    def test_case(self, dic):\n        logger.debug(f\"====>{dic}\")\n        # 判断是否有依赖,执行依赖接口替换依赖字段\n        ps = PreSolve(test_data)\n        dic[\"header\"], dic[\"value\"] = ps.presolve(dic)\n        #实例化\n        ch = ConfigHttp(dic)\n        #调用实例方法\n        res = ch.run()\n        # 将响应的json数据转化成字典\n        res_dict = res.json()\n    \n        # 坑一：用if断言需在失败情况下抛出assertion\n        # if str(res_dict[\"errorCode\"]) == str(dic[\"expect\"]):\n        #     print(\"用例执行成功\")\n        # else:\n        #     print(\"用例执行失败\")\n        #     raise AssertionError(\"预期结果与实际结果不符\")\n    \n        # 坑二：try-except不要加在self.assertEqual前后，否则unittest捕获不到AssertionError,就默认为用例通过\n        # try:\n        #     assert str(res_dict[\"errorCode\"]) ==str(dic[\"expect\"]), f\"预期结果与实际结果不符，预期结果：{dic['except']},实际结果：{res_dict['errorCode']}\"\n        # except Exception as msg:\n        #     print(f\"报错信息：{msg}\")\n        #     raise\n    \n        # 2.1.3断言返回的实际结果，断言用例执行成功/失败\n>       assert str(res_dict[\"errorCode\"]) == str(dic[\"expect\"]), f\"预期结果与实际结果不符，预期结果：{dic['expect']},实际结果：{res_dict['errorCode']}\"\nE       AssertionError: 预期结果与实际结果不符，预期结果：{'errorCode':'0'},实际结果：0\nE       assert '0' == \"{'errorCode':'0'}\"\nE         - {'errorCode':'0'}\nE         + 0\n\ntestCase/test_case.py:54: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"AssertionError: 预期结果与实际结果不符，预期结果：{'errorCode':'0'},实际结果：0\nassert '0' == \"{'errorCode':'0'}\"\n  - {'errorCode':'0'}\n  + 0","statusTrace":"self = <testCase.test_case.TestCase object at 0x11023a320>\ndic = {'caseid': '', 'expect': \"{'errorCode':'0'}\", 'header': '{}', 'id': 3.0, ...}\n\n    @pytest.mark.parametrize(\"dic\", test_data)\n    def test_case(self, dic):\n        logger.debug(f\"====>{dic}\")\n        # 判断是否有依赖,执行依赖接口替换依赖字段\n        ps = PreSolve(test_data)\n        dic[\"header\"], dic[\"value\"] = ps.presolve(dic)\n        #实例化\n        ch = ConfigHttp(dic)\n        #调用实例方法\n        res = ch.run()\n        # 将响应的json数据转化成字典\n        res_dict = res.json()\n    \n        # 坑一：用if断言需在失败情况下抛出assertion\n        # if str(res_dict[\"errorCode\"]) == str(dic[\"expect\"]):\n        #     print(\"用例执行成功\")\n        # else:\n        #     print(\"用例执行失败\")\n        #     raise AssertionError(\"预期结果与实际结果不符\")\n    \n        # 坑二：try-except不要加在self.assertEqual前后，否则unittest捕获不到AssertionError,就默认为用例通过\n        # try:\n        #     assert str(res_dict[\"errorCode\"]) ==str(dic[\"expect\"]), f\"预期结果与实际结果不符，预期结果：{dic['except']},实际结果：{res_dict['errorCode']}\"\n        # except Exception as msg:\n        #     print(f\"报错信息：{msg}\")\n        #     raise\n    \n        # 2.1.3断言返回的实际结果，断言用例执行成功/失败\n>       assert str(res_dict[\"errorCode\"]) == str(dic[\"expect\"]), f\"预期结果与实际结果不符，预期结果：{dic['expect']},实际结果：{res_dict['errorCode']}\"\nE       AssertionError: 预期结果与实际结果不符，预期结果：{'errorCode':'0'},实际结果：0\nE       assert '0' == \"{'errorCode':'0'}\"\nE         - {'errorCode':'0'}\nE         + 0\n\ntestCase/test_case.py:54: AssertionError","steps":[],"attachments":[{"uid":"5cc1bb0f4a74d9e6","name":"log","source":"5cc1bb0f4a74d9e6.txt","type":"text/plain","size":324}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"testCase"},{"name":"suite","value":"test_case"},{"name":"subSuite","value":"TestCase"},{"name":"host","value":"liushadeMBP"},{"name":"thread","value":"9552-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"testCase.test_case"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"dic","value":"{'id': 3.0, 'interfaceUrl': 'https://www.wanandroid.com/user/logout/json', 'name': 'logout', 'method': 'get', 'value': \"{'username':'liusha'}\", 'header': '{}', 'rely': 'n', 'caseid': '', 'expect': \"{'errorCode':'0'}\"}"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"88665c8383de55ab.json","parameterValues":["{'id': 3.0, 'interfaceUrl': 'https://www.wanandroid.com/user/logout/json', 'name': 'logout', 'method': 'get', 'value': \"{'username':'liusha'}\", 'header': '{}', 'rely': 'n', 'caseid': '', 'expect': \"{'errorCode':'0'}\"}"]}